### ISSUE TITLE
 Is the project abandoned? 

### ISSUE THREAD

**Issue by krenXlil** [MrMelon54/extra-armour-info-fabric#3]
I really want to see this mod on 1.20. At least just a port without new features

**Comment by mrmelon54** [comment]
Nah, its only been a week since the 1.20 release and I have other mods to update as well

**Comment by mrmelon54** [comment]
was going to leave it for the other dev to update
but turns out I'm updating it now

**Comment by mrmelon54** [comment]
Future development on https://github.com/mrmelon54/extra_armor_info
